-- MySQL Script generated by MySQL Workbench
-- Mon Jun  7 14:54:32 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projetwebbdd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projetwebbdd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projetwebbdd` DEFAULT CHARACTER SET utf8 ;
USE `projetwebbdd` ;

-- -----------------------------------------------------
-- Table `projetwebbdd`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetwebbdd`.`Users` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(255) NULL,
  `autorisation` TINYINT NULL,
  `phoneNumber` INT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetwebbdd`.`Movies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetwebbdd`.`Movies` (
  `idMovies` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(45) NULL,
  `Description` VARCHAR(1000) NULL,
  `Image` VARCHAR(150) NULL,
  UNIQUE INDEX `Title_UNIQUE` (`Title` ASC) VISIBLE,
  PRIMARY KEY (`idMovies`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetwebbdd`.`Rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetwebbdd`.`Rooms` (
  `idRooms` INT NOT NULL AUTO_INCREMENT,
  `RoomCapacity` INT NULL,
  PRIMARY KEY (`idRooms`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetwebbdd`.`Planning`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetwebbdd`.`Planning` (
  `idPlanning` INT NOT NULL AUTO_INCREMENT,
  `Date` DATETIME NULL,
  `Movies_idMovies` INT NOT NULL,
  `Rooms_idRooms` INT NOT NULL,
  PRIMARY KEY (`idPlanning`),
  INDEX `fk_Planning_Movies1_idx` (`Movies_idMovies` ASC) VISIBLE,
  INDEX `fk_Planning_Rooms1_idx` (`Rooms_idRooms` ASC) VISIBLE,
  CONSTRAINT `fk_Planning_Movies1`
    FOREIGN KEY (`Movies_idMovies`)
    REFERENCES `projetwebbdd`.`Movies` (`idMovies`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Planning_Rooms1`
    FOREIGN KEY (`Rooms_idRooms`)
    REFERENCES `projetwebbdd`.`Rooms` (`idRooms`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetwebbdd`.`Reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetwebbdd`.`Reservation` (
  `idRéservation` INT NOT NULL AUTO_INCREMENT,
  `Users_idUser` INT NOT NULL,
  `Planning_idPlanning` INT NOT NULL,
  PRIMARY KEY (`idRéservation`),
  UNIQUE INDEX `idRéservation_UNIQUE` (`idRéservation` ASC) VISIBLE,
  INDEX `fk_Reservation_Users_idx` (`Users_idUser` ASC) VISIBLE,
  INDEX `fk_Reservation_Planning1_idx` (`Planning_idPlanning` ASC) VISIBLE,
  CONSTRAINT `fk_Reservation_Users`
    FOREIGN KEY (`Users_idUser`)
    REFERENCES `projetwebbdd`.`Users` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservation_Planning1`
    FOREIGN KEY (`Planning_idPlanning`)
    REFERENCES `projetwebbdd`.`Planning` (`idPlanning`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
